################################################################################
# FUNDING.yml for Ultrahand-Wallpaper Repository
# Author: ppkantorski
# Description:
#   This FUNDING.yml file is used to configure the sponsor button for the Ultrahand Wallpaper
#   repository on GitHub. It specifies the supported funding model platforms and their
#   respective account information.
#
#   GitHub Repository: https://github.com/ppkantorski/Ultrahand-Wallpaper
#
################################################################################

github: ppkantorski
ko_fi: ppkantorski
